#
# Use this file to register new configs related to Flux itself.
#
# Looking for Flux framework settings? Check out the settings.yml file!
#
# !!!!
# DO NOT USE THIS FILE TO REGISTER CONFIGURATION FOR YOUR SCHEMA
# OR PLUGIN.
#
# If you wish to add configuration to your plugin, create a similar
# file in the following path:
# plugins/<your_plugin>/plugin/config/config.yml
# gamemodes/<your_schema>/schema/config/config.yml
# !!!!
#
categories:
  general:
    name: config.general.title
    description: config.general.desc
configs:
  walk_speed:
    name: config.general.walk_speed.name
    description: config.general.walk_speed.desc
    category: general
    type: number
    min_value: 0
    max_value: 1024
    default_value: 100
  run_speed:
    name: config.general.run_speed.name
    description: config.general.run_speed.desc
    category: general
    type: number
    min_value: 0
    max_value: 1024
    default_value: 200
  crouched_speed:
    name: config.general.crouch_speed.name
    description: config.general.crouch_speed.desc
    category: general
    type: number
    min_value: 0
    max_value: 1024
    default_value: 50
  respawn_delay:
    name: config.general.respawn_time.name
    description: config.general.respawn_time.desc
    category: general
    type: number
    min_value: 0
    max_value: 600
    default_value: 30
  command_prefixes:
    name: config.general.prefixes.name
    description: config.general.prefixes.desc
    category: general
    type: table
    default_value: ["!", "/"]
  jump_power:
    name: config.general.jump_power.name
    description: config.general.jump_power.desc
    category: general
    type: number
    min_value: 0
    max_value: 1024
    default_value: 150
  data_save_interval:
    name: config.general.data_save_interval.name
    description: config.general.data_save_interval.desc
    category: general
    type: number
    min_value: 0
    max_value: 3600
    default_value: 360
  player_data_save_interval:
    name: config.general.player_data_save_interval.name
    description: config.general.player_data_save_interval.desc
    category: general
    type: number
    min_value: 0
    max_value: 3600
    default_value: 360
  root_steamid:
    name: config.general.root_steamid.name
    description: config.general.root_steamid.desc
    category: general
    type: table
    default_value: ["STEAM_0:0:000000000"]
